### ISSUE TITLE
Flag resource to prevent overwrite on update

### ISSUE THREAD

**Issue by kwaclaw** [RickStrahl/Westwind.Globalization#10]
We have a use case where localizations are initially supplied by us, but the customer may modify them.

When a software updated happens and  the initially installed localization resources would be updated we do not want to overwrite the customer's modifications.

How can that be achieved?

**Comment by RickStrahl** [comment]
That's not a scenario that's directly supported by Westwind.Globalization. 

However, you can probably merge the localization table with the data from your updated resources since the IDs generated are unique. 

There's no easy way to make this generic since it heavily depends on what resources 'win' when you compare. I suppose it might be a good idea to add an Updated flag to the default table so we could also see last time the resources were modified. I'll put that on the todo list.

**Comment by kwaclaw** [comment]
Thanks for the quick reply. Yes, an Updated flag would be helpful.

**Comment by RickStrahl** [comment]
Updated flag is part of the latest beta release.
