### ISSUE TITLE
Auto create Localizations tables

### ISSUE THREAD

**Issue by fujoos** [RickStrahl/Westwind.Globalization#107]
Thanks for the wonderful localization package that is West Wind Globalization. The challenge we are having is the creation of the Localization table. We want to auto create it in Entity Framework and seed data but no matter how we mirror the tables to the Localization table provided when you manually create it in index.html, it still doesn't work. Importing of resources doesn't work either. Are there some extra settings made after creating the table via the Administration index page?
Do you also have plans to create an MVC design for the index page in the Localization Admin?

**Comment by RickStrahl** [comment]
There's nothing special about the table structure used by the localization tables. They are on purpose as basic as possible in order to ensure that the table works on various databases. It's a single table and there are no Fk rules etc. that should be a problem.

If Entity Framework isn't creating the table correctly you can always use explict SQL commands in your migrations to match the format by copying the same SQL that WWG uses.

* [Table Schema](https://github.com/RickStrahl/Westwind.Globalization/blob/master/src/Westwind.Globalization/DbResourceDataManager/DbResourceDataManagers/DbResourceSqlServerDataManager.cs)

Other than that just make sure your connection strings are properly set up both for EF and for WWG.
