### ISSUE TITLE
secure Administration Web UI 

### ISSUE THREAD

**Issue by TheSniper102** [RickStrahl/Westwind.Globalization#109]
There is no way to secure Administration Web UI in asp.net mvc Project

**Comment by RickStrahl** [comment]
Sure there is - you can use web.config security and lock down the folder to require authentication. You just can't use Authorization filters because the admin API is not an MVC application (so that it can be used in any kind of System.Web application).

This should work:

```xml
<configuration>
    <location path="LocalizationAdmin">
        <system.web>
            <authorization>
                <allow users ="*" />
            </authorization>
        </system.web>
    </location>
</configuration>
```

Now you have to authenticate before you can access anything LocalizationAdmin folder which includes the HTML page and API.

There are additional options on Authorization that can redirect to a login page.
