### ISSUE TITLE
Question: What is the best point to read resources from an API.

### ISSUE THREAD

**Issue by papauorg** [RickStrahl/Westwind.Globalization#122]
Hello,

I recently started using the Westwind.Globalization package. It's really helpful, thank you for the time you invested in it. Good work! :)

I have a scenario where multiple apps use the same resources for translating texts for the UI. I don't want the Apps to have direct access to the database, so I introduced an api that has an endpoint for retrieving the resources by ResourceSet and LocaleId. The same api also hosts the LocalizationAdmin for translating texts. It otherwise uses the Westwind.Globalization package as provided by you and is configured according to the documentation.
```
WebApp 1   ------- HTTP -- \
                             -- > REST API Endpoint for ResourceSets
WebApp 2   ------- HTTP -- /
```

I'm now trying to figure out where to extend/add functionality to call this api to retrieve the resources instead of the database. It would be great to make use of the already available functionality of your Package (such as IStringLocalizer, IHtmlLocalizer for AspnetCore and DBRes for the others). 

I had a look at the code and it seemed that a good point to start would be to have a custom implementation of the DBResourceReader because there the resources will be retrieved from the DB. But I saw that the DBResourceReader can not be easily replaced because it is directly instantiated by the DBResourceSet which in turn is directly instantiated by the DbResourceManager ... and so on.

Is there a way to easily provide a "read-only" source for the resources without having to reimplement all those classes? Do you have a suggestion for me?

Thank you very much and best regards,
Philipp

**Comment by RickStrahl** [comment]
The resource provider architecture is unfortunately terrible in .NET and there's no easy way to just instantiate pieces of it - it's all or nothing and that's really due to the .NET implementation which is a big pain in the rear to implement :-)

However, Westwind.Globalization does have a 'front-end' for the DB Resources it's managing in the `DbResourceDataManager` which offers a higher level API. That's also what the existing REST API uses and it provides the high level methods to retrieve individual values, or various lists.

There's the JavaScript Resource provider that can inject JS resources into a page - it has the option of reading data from the Db or from RESX resources. You can either use that directly by pointing your app to the central 'repository' or you can use that code as the starting point for building something different.

Just be aware once you have RESX resources you have a lot less flexibility to return data in any shape other than individual values or the entire resource set.

**Comment by papauorg** [comment]
Thank you for your response, Rick. 

I'm not sure I understand correctly. I saw that there are `DBResourceDataManager` implementations. But they are very database specific (e.g. The methods for creating tables or GetDb). Also they provide much more functionality that I would need in the Client applications. They only require read access. Could the other methods safely throw a NotSupportedException? Also how would I get the Westwind library to use my implementation (on the client side) instead of the 4 already available ones?

About the Javascript resource provider: I could use it if it were a single page application or only requesting texts from the browser, is this correct? I couldn't use it from a .NET application - which I intend to do.

I tried to illustrate what I mean in the image.
![Resource Reading](https://user-images.githubusercontent.com/2471424/37390650-18eaaef6-2769-11e8-8cdd-fefbc43013dd.png)

What I try to do is use the Westwind.Globalization Library in my "translation service" as well as in the Application that needs access to the resources. I'd love to use the already existing features such as the localizers, localizer factories and the whole language fallback feature and caching. So I just tried to replace the only relevant change for this case which seemed to be the DBResourceReader (as seen in the PR #123). I'm not sure what I would have to do to implement a custom DBResourceDataManager.

Could you give me another hint please? And sorry if I didn't understand correctly.

Thank you very much!

**Comment by papauorg** [comment]
I sucessfully tried to use a custom implementation of the `DBResourceDataManager` in which I only implemented the GetResourceSet method. 

Now the flow is:
`App Logic --> IStringLocalizer --> Westwind.Globalization --> Custom DBResourceDataManager --> REST API --> Westwind.Globalization.DBResourceSqlServerDataManager`

Seems to be working fine for my case. 

Thanks again for your hint! I will close this issue and the PR.
