### ISSUE TITLE
Could not load types

### ISSUE THREAD

**Issue by thehaunt** [RickStrahl/Westwind.Globalization#13]
I'm not sure what I am missing, but I don't seem to be able to shake these two errors when installing this package via nuget:

Error	32	Could not load type 'Westwind.GlobalizationWeb.LocalizationAdmin_StronglyTypedGlobalResources'.

Error	31	Could not load type 'Westwind.GlobalizationWeb.LocalizeAdmin'.	Z:\LanguageTest2

I thought it might have something to do with the DbResourceProvider configuration, but I can't seem to figure it out.

In the auto-configuration, I get nearly what you have posted on the GitHub page, but instead of:

resourceNamespace="AppResources"

it is set to:

resourceBaseNamespace="MyApplication.Properties"

Note that the attributes have different names.  Changing this around doesn't seem to help.

Any ideas on how I might correct this error?

**Comment by RickStrahl** [comment]
That sounds like missing strongly typed resources. Let me check and see what's going on. 

What version of the NuGet package are you using?

**Comment by RickStrahl** [comment]
So I checked this out off a fresh install from the latest non-preview NuGet package. Code Compiles and runs without any issues. So not sure what's happening.

Please provide steps of what you did to run your project...

**Comment by thehaunt** [comment]
Using VisuaI Studio Professional 2013, I created a new web application project (.NET 4.5) and ran the  install command from the package command line tool.  It installed Globalization version 1.998, Ajax Libraries 2.59 and WestWind.Utilities 2.59.1.

After that I added a connection string to the Web.Config and updated the DbResourceProvider to include the connection.  The errors I mentioned were present through all steps.  Fiddling with the DbResourceProvider did not help.

Is there some way we can exchange projects?  I can zip up the one I'm having issues with and you can send me the test you created?

**Comment by RickStrahl** [comment]
For my part I simply created a new MVC project and added the localization provider. Pointed it at my existing localization db and it all just works.

I think the problem is that you're using a Web site, not a Web Project. The administration pages are WebForms pages that use the Application Project format and that doesn't work in Web Projects.

The next version which is getting ready to be released removes this limitation as the administration form is a AJAX HTML application.

So for now your choices are:
* Switch to a Web Application Project (ie. create new Project instead Create New WebSite)
* Try the latest bits - and remove the LocalizationAdmin folder

There are no NuGet packages for the new bits yet so you'd have to use the code from the actual GIT repository. If you can wait for a few days I should have preview packages out by this weekend. the new providers and admin interface offer a host of new features so it might be worthwhile to wait anyway.

**Comment by thehaunt** [comment]
Many thanks for taking a look, adding it to an empty MVC project did the trick.  As you said, I was also able to get the package working in a website by removing the LocalizationAdmin stuff.  Looking forward to the next version!

On a side note, I want to extend you a huge thank you as your blogs have been a big part of my education over the years.  Know that your work reaches and is appreciated by a great many people, myself among them.

**Comment by RickStrahl** [comment]
Thanks appreciate that.

Just to be clear - the LocalizationAdmin folder and forms work fine in a Web Application as is. For a Web Site the forms need to be changed using the Web site form syntax which is different (Code instead of CodeBehind etc.). Luckily going forward this won't be an issue with the new admin interface not using server side UI at all.
