### ISSUE TITLE
Resource is not added if differs casing.

### ISSUE THREAD

**Issue by ivarsst** [RickStrahl/Westwind.Globalization#132]
Hello!
There is a problem with "AddMissingResources" and resource keys, that differs in casing. If "foo" is already added to DB, then "Foo" will not be added to DB. The worst thing, that "foo" will not be returned too - it will just keep trying to add "Foo" as new resource, and not caching the returned result. So, every time, when application will call for "Foo", there will be call to DB. As a result - dangerous performance issues.

**Comment by RickStrahl** [comment]
Casing depends on your database settings. If your database is set to use case insensitive data then the case will effectively be ignored. Otherwise it will not.

As to performance - WriteValues should be a development time setting only - you shouldn't run in production with that. In fact, if performance matters you shouldn't use the database at all but export to Resx and run with that in production.

I'll take a look and see what is actually happening for the update code. It's been a long time that i"ve looked at that bit.

**Comment by RickStrahl** [comment]
So I took another look. The way it works is the way it should work IMHO.

* The lookup for the ResourceId is Case Sensitive 
* If you mismatch case the ResourceSet won't match it
* Then the code to AddMissing Resource is fired
* It hits the database and checks for the value

* IF THE DB IS NOT CASE SENSITIVE IT'LL JUST RETURN THE VALUE
* THIS WILL KEEP LOOKING UP THE VALUE (as you pointed out - which is not efficient)

* If the Db is case sensitive it won't find the value
* The value is then inserted with the proper name
* Next hit the value will be in the ResourceSet with both cases

So, as you point out there's a use case where you can find every hit to a case mismatched value going to the database. But I don't see how we can fix this - the problem here is that the database is not matching case exactly and that's causing this loop. 

However, the ResourceSet will always miss a non-exact match and that is the correct behavior. So the fact that AddMissingResources hits the db and gets the value back if the DB can't match is incidental. And as I pointed out you really shouldn't use AddMissingResources in production when performance matters, regardless of this issue.

**Comment by ivarsst** [comment]
thank you, Rick! Keep up great work!
