### ISSUE TITLE
Resx file generator does not write xml declarations

### ISSUE THREAD

**Issue by rintje** [RickStrahl/Westwind.Globalization#3]
Hi Rick,

DbResXConverter writes resx files without a proper xml declaration.

The culprit seems to be Westwind.Globalization/SupportClasses/DbResXConverter.cs, line 337. This line intends to write the xml template to file by writing the root child element, thereby ignoring the xml declaration.

**Comment by RickStrahl** [comment]
Apologize for missing this for so long. Added the appropriate processing instruction header.

FWIW, while it's certainly better to write the PI, have you actually seen a failure because of it? The stock PI and default formatting for XmlWriter should not cause any problems if the PI is actually missing.

**Comment by rintje** [comment]
Great, thanx for fixing it anyway. 

According to my collegae, Visual Studio did have problems reading the resx files without the xml declaration. (Otherwise he would not have made a problem about it ;-))
