### ISSUE TITLE
import resources not possible when table in DB is empty

### ISSUE THREAD

**Issue by okli23** [RickStrahl/Westwind.Globalization#40]
Import resources is not possible when table in DB is empty.
How to reproduce:
1. create table
2. remove sample values from db (`delete from localizations;`)
3. bug: only 'create table' button is available and when clicked there is a message 'LocalizationTableNotCreated Localization Table exists already'

**Comment by RickStrahl** [comment]
Yes, that's not optimal but is by design - not optimal but reasonable as we do create the default resources. If I recall the issue is reliably determining whether a table exists in various providers. Current code checks if the record set comes back empty.

The workaround is to add a new resource before deleting the table.
