### ISSUE TITLE
Search on Web AdminLocalization hangs for large data sets

### ISSUE THREAD

**Issue by okli23** [RickStrahl/Westwind.Globalization#41]
There is a performance problem for large data sets - the page just crashes.
I was tested it for around 7k resources in 20 locales.
The problem is caused by this line:
```html
ng-repeat="resource in view.resourceList | filter:view.searchText"
```
It's a pretty well known problem of angular, some possible solutions are described here:
http://tech.small-improvements.com/2013/09/10/angularjs-performance-with-large-lists/

**Comment by RickStrahl** [comment]
Hmmm... that seems pretty extreme. Aren't you using resource sets to segment your resources a bit than having 7000 resources in one set? That would seem terribly unmanagable in general as there have to be tons of near duplicate keys.

I looked at some of the work arounds and I'm not sure that they apply because we're doing a list reduction filter. In order for that to work the data has to all be there. I have a couple of very large projects (which I think are nearly unmanagable) that use about 1500 resources and that seems to work without much delay. The breaking point is likely much higher than that.

In your case the best solution might just be to remove the filter altogether. What does perf look like without it?

**Comment by okli23** [comment]
Loading of this whole resourceSet takes around 15 seconds, but then it's fully usable - you can scroll the list without any problems.  
Only if you start typing anything in the search box, Chrome hangs with 100% CPU usage.

In general I do agree that having smaller resource sets would be more manageable, but there is not much I can do about it for now unfortunately. :(

**Comment by RickStrahl** [comment]
Any chance you can send me your test data as a SQL trace? I suppose I can generate some data but be easier if I have a premade setup.

**Comment by okli23** [comment]
I'm afraid I cannot share my valuable resources ;), but please generate data using the below:

```sql
drop procedure if exists load_test_data;

delimiter $
create procedure load_test_data()
begin

declare v_max int unsigned default 4000;
declare v_counter int unsigned default 0;

  truncate table localizations_temp;
  alter table localizations_temp AUTO_INCREMENT = 1;
  insert into localizations_temp (ResourceId, ResourceSet, Value) values ('Hello', 'smallSet', 'Hello');
  
  while v_counter < v_max do
    insert into localizations_temp (ResourceId, ResourceSet, Value) 
	 	values ( CONCAT(v_counter, '_stringToMakeValueLonger'), 'veryBigSet', v_counter );
    set v_counter=v_counter+1;
  end while;
  
end $

delimiter ;

call load_test_data();
```

**Comment by RickStrahl** [comment]
Put off for later review as this seems to be an exceptional case of way to many resources in a single resource set. The best solution I can suggest is to break up resources into multiple resource sets. Testing with around 1500 resources appears to yield decent search performance but it does start dropping off after that. 

For now this is not a high priority.
