### ISSUE TITLE
Google Translation issue

### ISSUE THREAD

**Issue by akshukla009** [RickStrahl/Westwind.Globalization#53]
Google translation not working 
.
Error Details:

Connection failed: : The remote server returned an error: (403) Forbidden.

**Comment by RickStrahl** [comment]
Yes I see that. Unfortunately it looks like Google has finally cut off the free Google Translate hacks that I'd been using for doing the Google translation. 

At this point this will be broken. I'll add support for the proper Google Translate API, but there is unfortunately no longer any free level to this API, so an API key will be needed to get that to work.

**Comment by RickStrahl** [comment]
Updated support for 'free' Google Translate API used from Google Translator's Web site which is an unofficial API that might not work if abused or if Google decides to change the API. Use at your own risk knowing it might be shut off at any time due to quota or Google Policy.

Added support for official Google Translate API v2. If you provide a Google API key for the Translate API the full paid for Google API is used.
