### ISSUE TITLE
Resx export trouble if resource set contains a period

### ISSUE THREAD

**Issue by peaeater** [RickStrahl/Westwind.Globalization#54]
To help myself find a resource set real quick, I named them after my MVC views: Home.cshtml, _Layout.cshtml, etc. When exporting 'all resource sets' to resx, just a '.resx' file is produced, with the contents of a single resource set.

**Comment by RickStrahl** [comment]
Yes that's a known issue because it uses the `.` to differentiate WebForms resourcesets based on the . (since WebForms uses page names) to figure out that it should use local and global resources. Using the . was a generic way to do but we couldn't use fixed file extensions due to the fact (including myself) that many people used custom extensions for WebForms pages.

So for now you can't use `.` in the name. You can replace the `.` with another character like `_`.
