### ISSUE TITLE
Search by translation

### ISSUE THREAD

**Issue by vovikdrg** [RickStrahl/Westwind.Globalization#67]
I would like to have possibility to search not only by key of resource but also by value. 

I also can do pull request for that

**Comment by RickStrahl** [comment]
Well the problem is in the client UI the search looks just at the actual values that are in the list on the client side. The actual values are not loaded and searchable in the simple list popup.

I think if you need more full featured search operations, we'd need to add a real search button that goes back to he DB to search resources and returns a result to pick from.

**Comment by vovikdrg** [comment]
Actually I solve my issue by using grid, but still at some point i am thinking about feature like show items without translations.

**Comment by RickStrahl** [comment]
Yes the Grid view is the easiest way to do this.

I've considered this a few times, but I can't think of a good UI to represent this. My initial thought was to flag items in the resource list on the left if localizations are missing, but keeping that in sync - especially if the list of resources is large is going to get slow.
