### ISSUE TITLE
Solution not working with SQL CE

### ISSUE THREAD

**Issue by Coyote78** [RickStrahl/Westwind.Globalization#8]
After trying various configurations, it doesn't seem possible to make it work with SQL CE local file :(

It looks like it is not using correct Provider for CE file, but always use full SQL Server provider

**Comment by RickStrahl** [comment]
Thanks for the feedback. Turns out there was a bug in the Configuration provider that always parsed the connection string, so the DAL never got notified of the other provider.

Please check the Devolopment Branch:  37d76eb

This should fix this problem. The provider will work and the basic edit features should come up. Not quite sure if all update and export operations will work, but will check on that later.

FWIW, I'm working on the next version that will have better support for pluggable data providers.

**Comment by Coyote78** [comment]
Great, thank you for the quick feedback !

Sample solution works as described.
I'll implement it in my project and let you know if I encounter other issues
