### ISSUE TITLE
"Generate Local Resources" breaks

### ISSUE THREAD

**Issue by Alucardz** [RickStrahl/Westwind.Globalization#80]
I'm using VS 2012, and the 'Tools -> Generate Local Resources' option is giving out an error in the Output window saying:

```
Start creating resource content and adding 'meta' attributes to server controls and directives.
Invalid Connection string name.: *** ENTER A CONNECTION STRING OR connectionStrings ENTRY HERE ***
Finished creating resource content and adding 'meta' attributes.
```

My web.config does NOT contain that value anymore, I've input a working connection string; The LocalizationAdmin tool is working fine, the resource table has been created correctly and all is dandy...

Except the"Generate Local Resource" option doesn't work anymore.

Anything I can do to remedy that?

Thanks in advance.

Edit: Temporary fix is to remove the `<globalization .../>` tag in the web.config before generating and place it back afterwards.... 

I suspect this has something to do with the VS design-time behavior relying on default values from the `DbResourceConfiguration ` '`ConnectionString`' property... which is hard-coded to be "`*** ENTER A CONNECTION STRING OR connectionStrings ENTRY HERE ***`" and expected to be overridden by the web.config at run-time; but since this is design-time the value doesn't get updated.

**Comment by RickStrahl** [comment]
Unfortunately the tooling has changed in Visual Studio and has broken the behavior of the generate local resources. The problem is that the internal VS usage behaves different than the live provider. I'm glad it works with your temporary fix - your effectively bypassing the ASP.NET Resource Provider and just letting WWG do its thing internally which is why that works.

I have to take another look at that, but frankly I'm wary to continue to support this since this is a retired feature in VS (I can't even get it to work in VS2015 at all for standard resources). 

Thanks for the report
