### ISSUE TITLE
Unit Testing 

### ISSUE THREAD

**Issue by Sarvesh-Gupta** [RickStrahl/Westwind.Globalization#93]
How do I unit test ViewModelWithLocalizedAttributes. I don't want to actually hit the database, but mock the resource strings.

**Comment by RickStrahl** [comment]
I don't know - there's really no good way of doing this because you're dealing with static properties. 

The only thing I can think of is create a custom DbResourceProvider that uses memory to feed that data for GetResourceSet() (which is what ultimately feeds the resource data in the ResourceManager).
