### ISSUE TITLE
Painful adding support for Azure Table Storage

### ISSUE THREAD

**Issue by malcolmohare** [RickStrahl/Westwind.Globalization#94]
I'm integrating this package into my ASP MVC webpage and I want to use Azure Table Storage as the datastore instead of an RDS.  It's feeling like a painful slog to make this happen, so either I'm doing it wrong or there's some room for refactoring in the code base.  

The implementation i'm working on is creating a new ResourceDataManager (RDM) class that hooks up to Table Storage instead of a RDS.  Is this the correct thing to do?

I was hoping I'd just be able to change out the data interface, but there's a lot of coupling between querying and transforming the query data in the RDM.

Has anyone worked on / implemented a Table Storage version before I spend too much time on this?  Or do you want this code available for commiting if I can get it working?

**Comment by RickStrahl** [comment]
Understood. But the provider is pretty old and was designed with SQL data sources in mind. The Sql data sources can pretty much inherit existing interface and just override any place where non-standard SQL is required so it's fairly easy to do.

But any non-SQL source basically has to reimplement all the base interface methods since the SQL methods can't be inherited. I don't have a better answer than that I'm afraid.
